#ifndef CONSTS_H
#define CONSTS_H

#define MAX_NICK_SIZE 16
#define MAX_WORD_SIZE 16
#define MAX_HINT_SIZE 64
#define MAX_CMD_SIZE 32
#define REQ_QLEN 10
#define INIT_CLIENTS_ARR_SIZE 32
#define MAX_CLIENT_COUNT 10
#define MIN_CLIENT_COUNT 2
#define MAX_BUFFER_SIZE 512

#endif /*CONSTS_H*/
